configuration: ReleaseMono

environment:
  packageVersion: 1.7.6

version: $(packageVersion).{build}

cache:
- packages -> **\packages.config

services:
- mssql2012sp1
- mysql
- postgresql

init:
- cmd: git config --global core.autocrlf true
- ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: |
    if ($env:APPVEYOR_REPO_BRANCH -eq "release") 
    {
        $env:nugetVersion = "$env:packageVersion"
    }
    else
    {
        $env:nugetVersion = "$env:packageVersion-rc$env:appveyor_build_number"
    }
- ps: Update-AppveyorBuild -Version $env:buildVersion

nuget:
  account_feed: false
  project_feed: false

#before_build:
#- cmd: nuget restore linq2db.mono.sln

build_script:
- cmd: '"c:\Program Files (x86)\Mono\bin\xbuild" linq2db.mono.sln /p:Configuration=ReleaseMono'

#test: 
#  assemblies:
#    - \Tests\**\linq2db.Tests.dll

test_script:
- ps: |
    # try nunit3 
    nunit3-console.exe (Resolve-Path Tests\Linq\bin\ReleaseMono\linq2db.Tests.dll) --x86 --framework=mono-4.0
    $test1res = $LASTEXITCODE 
    # upload results to AppVeyor
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
    Push-AppveyorArtifact (Resolve-Path .\TestResult.xml)
    IF ($test1res -ne 0) { exit -1 }


before_test:
- ps: |
      Push-Location -Path Tests\Linq\bin\ReleaseMono
      cd $env:appveyor_build_folder
      . ".\Av-InitDatabases.ps1"

after_test:
- ps: Pop-Location
